### ISSUE TITLE
IsSteamFriend() Check

### ISSUE THREAD

**Issue by yash1441** [polvora/SteamCore#10]
I couldn't find it in SteamWorks so is it possible to add an IsSteamFriend() check?

**Comment by polvora** [comment]
I didn't directly add a native to check is someone is your friend. But now you can enable chat send the friend request and wait for `OnChatFriendStateChange()` to be called. if the `friend` parameter is the guy you added it means he accepted you.

Also as you own an inviter plugin, you can just send an invite without knowing if the account you invited is your friend, because is he is not, `errorCode == 0x28` will be returned and then you can add him and wait in chat till he connects. Also it doesn't matter if he has the chat disabled you will still get call from OnChatFriendStateChange().

Cheers!

**Comment by polvora** [comment]
Also read the new include file, i changed a lot of things (native calling and callbacks).
