### ISSUE TITLE
SteamTools Version

### ISSUE THREAD

**Issue by RumbleFrog** [polvora/SteamCore#3]
I read a reply saying that a mix of SteamTools and Steamworks can result in the other extension eating up the callback and someone of the users are using a mix of both. So, is it possible for you to create another branch that utilizes SteamTools instead? It won't be a big deal if you can't.

**Comment by polvora** [comment]
I am currently only solving high and critical bugs, maybe in the future i could just add some code to the current branch that checks which extension is loaded and use the according functions. 

I'll leave this issue open so in case a coder interested in adding this feature can see this and make a pull request.

**Comment by polvora** [comment]
I've thought about this but i don't see any evidence of callbacks being eaten, also SteamTools is only available to Tf2. I also read your posts in alliedmods and the guy talking about callbacks being eaten just said it as a posibility but you weren't mixing the extensions so that wasn't the case

I'll reopen this issue if new evidence comes up, thanks for the idea.
