### ISSUE TITLE
How to install SteamWorks?

### ISSUE THREAD

**Issue by Bl4CkGuuN** [polvora/SteamCore#7]
Im on the site but I dont know what to download or install..

**Comment by polvora** [comment]
http://users.alliedmods.net/~kyles/builds/SteamWorks/  Go to that site download the file that corresponds to the operative system of your server, and then the procedure is the same as for plugins, just copy all the content of the compressed file inside your server directory.

To figure out the operative system running your server, check the extensions folder in the sourcemod directory, if the files inside have .dll extension it means its Windows otherwise its Linux

**Comment by Bl4CkGuuN** [comment]
Cool, thank you :)
